#!/bin/bash
#SBATCH --time=24:00:00
#SBATCH --mem=64G
#SBATCH --mail-type=ALL
#SBATCH --mail-user=arjen.cupido@gmail.com


/hpc/dhl_ec/arjencupido/R-4.0.3/bin/Rscript /hpc/dhl_ec/arjencupido/UKB_scripts/20210129_NEW/script3_merge_genotype_phenotype.r
